rental_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rentals.urls')),
    path('users/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/authentication/password_reset.html'),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentals/urls.py
from django.urls import path

from rentals import views
from rentals.views import PropertyCreateView, PropertyDetailView, PropertyUpdateView, PropertyDeleteView


app_name = 'rentals'
urlpatterns = [
    path('', views.index, name='home_page'),
    path('property/new/', PropertyCreateView.as_view(), name='create_property'),
    path('property/<int:pk>', PropertyDetailView.as_view(), name='property_detail'),
    path('property/<int:pk>/update', PropertyUpdateView.as_view(), name='property_update'),
    path('property/<int:pk>/delete', PropertyDeleteView.as_view(), name='property_delete'),
    path('<username>/property/', views.owned_property, name='owned_property'),
]

users/urls.py
from django.urls import path

from users.views import TenantSignUpView, LandlordSignUpView, ApplicationCreateView, ApplicationDetailView, \
    ApplicationListView
from users import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('signup/tenant/', TenantSignUpView.as_view(), name='tenant_signup'),
    path('signup/landlord/', LandlordSignUpView.as_view(), name='landlord_signup'),
    path('<username>/profile/', views.user_profile, name='user_profile'),
    path('application/new/', ApplicationCreateView.as_view(), name='application_create'),
    path('application/<int:pk>', ApplicationDetailView.as_view(), name='application_detail'),
    path('applications/', ApplicationListView.as_view(), name='application_list'),
]

templates/partials/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="#">
            <!--suppress CheckImageSize -->
            <img src="/media/rental_logo.png" width="30" height="30" class="d-inline-block align-top border border-dark rounded" alt="">
            Rental System
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'rentals:home_page' %}">Properties <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rentals:create_property' %}">List a Property</a>
                </li>
            </ul>
            <ul class="navbar-nav mt-2 mt-lg-0">
                {% if user.is_authenticated %}
                    {% if user.is_landlord %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:application_list' %}">Tenant Applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rentals:owned_property' user.username %}">My Properties</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:application_list' %}">My applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Saved Properties</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:user_profile' user.username %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partials/property_datails.html
<div class="col-sm-6 bg-light">
    <div class="media content-section">
        <div class="media-body">
            <div class="property-metadata">
                <span class="font-weight-light">Landlord: </span>
                <a class="mr-2" href="#">{{ object.owner }}</a>
                {% if object.owner.phone_number %}
                    <small class="text-muted">{{ object.owner.phone_number }}</small>
                {% else %}
                    <small class="text-muted">{{ object.owner.user.email }}</small>
                {% endif %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-2 mb-1" href="{% url 'rentals:property_update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-2 mb-1" href="{% url 'rentals:property_delete' object.id %}">Delete</a>
                </div>
            </div>
            <h2 class="lead property-title text-center">{{ object.name }}</h2>
            <div class="d-flex flex-row justify-content-center">
                <img class="img-fluid w-100"  src="{{ object.image.url }}">
            </div>
            <p class="property-content"><span class="font-weight-light text-info">Description: </span>{{ object.description }}</p>
            <div>
                <small class="text-muted">{{ object.address }}</small> |
                <small class="text-muted">UGX {{ object.price|intcomma }}</small> |
                <small class="text-muted">{{ object.category }}</small> |
                <small class="text-muted">{{ object.date_listed|date:"F d, Y" }}</small>
            </div>
        </div>
    </div>
</div>