rental_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rentals.urls')),
    path('users/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/authentication/password_reset.html'),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/authentication/password_reset_complete.html'),
         name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentals/urls.py
from django.urls import path

from rentals import views
from rentals.views import PropertyCreateView, PropertyDetailView, PropertyUpdateView, PropertyDeleteView


app_name = 'rentals'
urlpatterns = [
    path('', views.index, name='home_page'),
    path('property/new/', PropertyCreateView.as_view(), name='create_property'),
    path('property/<int:pk>', PropertyDetailView.as_view(), name='property_detail'),
    path('property/<int:pk>/update', PropertyUpdateView.as_view(), name='property_update'),
    path('property/<int:pk>/delete', PropertyDeleteView.as_view(), name='property_delete'),
    path('<username>/property/', views.owned_property, name='owned_property'),
]

users/urls.py
from django.urls import path

from users.views import TenantSignUpView, LandlordSignUpView, ApplicationCreateView, ApplicationDetailView, \
    ApplicationListView
from users import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('signup/tenant/', TenantSignUpView.as_view(), name='tenant_signup'),
    path('signup/landlord/', LandlordSignUpView.as_view(), name='landlord_signup'),
    path('<username>/profile/', views.user_profile, name='user_profile'),
    path('application/new/', ApplicationCreateView.as_view(), name='application_create'),
    path('application/<int:pk>', ApplicationDetailView.as_view(), name='application_detail'),
    path('applications/', ApplicationListView.as_view(), name='application_list'),
]

rentals/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Property(models.Model):
    owner = models.ForeignKey('users.LandLord', on_delete=models.CASCADE, editable=False)
    name = models.CharField(max_length=100, null=True)
    image = models.ImageField(default='img_default.png', upload_to='property_imgs')
    description = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    date_listed = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('rentals:property_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

rentals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from rentals.models import Property
from users.models import LandLord


def index(request):
    properties = Property.objects.all()
    context = {
        'title': 'Properties for rent',
        'properties': properties
    }
    return render(request, 'rentals/index.html', context)


def owned_property(request, username):
    landlord = LandLord.objects.filter(user__username=username).first()
    user_property = landlord.property_set.all()

    context = {
        'user_property': user_property
    }
    return render(request, 'rentals/my_properties.html', context)


class PropertyCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Property
    fields = ['name', 'image', 'description', 'address', 'price', 'category']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'List a Property'
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user.landlord
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_landlord:
            return True
        return False


class PropertyDetailView(DetailView):
    model = Property


class PropertyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Property
    fields = ['name', 'image', 'description', 'address', 'price', 'category']

    def form_valid(self, form):
        form.instance.owner = self.request.user.landlord
        return super().form_valid(form)

    def test_func(self):
        user_property = self.get_object()
        if self.request.user == user_property.owner.user:
            return True
        return False


class PropertyDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Property
    success_url = '/'

    def test_func(self):
        user_property = self.get_object()
        if self.request.user == user_property.owner.user:
            return True
        return False

templates/rentals/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block  content %}
    <div class="jumbotron-fluid">
        <h1 class="display-3 text-info text-center border-bottom mt-5 mb-4 font-weight-light">
            Find your next home a click away...
        </h1>
    </div>
    <div class="container">
        <div class="row">
            {% for object in properties %}
                <div class="col-sm-6 bg-light">
                    <div class="media content-section">
                        <div class="media-body">
                            <div class="property-metadata">
                                <span class="font-weight-light">Landlord: </span>
                                <a class="mr-2" href="#">{{ object.owner }}</a>
                                {% if object.owner.phone_number %}
                                    <small class="text-muted">{{ object.owner.phone_number }}</small>
                                {% else %}
                                    <small class="text-muted">{{ object.owner.user.email }}</small>
                                {% endif %}
                                {% if object.owner.user == user %}
                                    <div>
                                        <a class="btn btn-secondary btn-sm mt-2 mb-1" href="{% url 'rentals:property_update' object.id %}">Update</a>
                                        <a class="btn btn-danger btn-sm mt-2 mb-1" href="{% url 'rentals:property_delete' object.id %}">Delete</a>
                                    </div>
                                {% elif user.is_tenant %}
                                    <div>
                                        <a class="btn btn-success btn-sm mt-1 mb-1" href="{% url 'users:application_create' %}">Apply</a>
                                    </div>
                                    <div>
                                        <a class="btn btn-success btn-sm mt-1 mb-1" href="#">Save</a>
                                    </div>
                                {% endif %}
                            </div>
                            <h2 class="lead property-title text-center">{{ object.name }}</h2>
                            <div class="d-flex flex-row justify-content-center">
                                <img class="img-fluid w-100"  src="{{ object.image.url }}">
                            </div>
                            <p class="property-content"><span class="font-weight-light text-info">Description: </span>{{ object.description }}</p>
                            <div>
                                <small class="text-muted">{{ object.address }}</small> |
                                <small class="text-muted">UGX {{ object.price|intcomma }}</small> |
                                <small class="text-muted">{{ object.category }}</small> |
                                <small class="text-muted">{{ object.date_listed|date:"F d, Y" }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/rentals/my_properties.html
{% extends 'base.html' %}
{% load humanize %}

{% block  content %}
    <div class="jumbotron-fluid">
        <h1 class="display-4 text-info text-center border-bottom mt-5 mb-4 font-weight-light">
            Property Management
        </h1>
    </div>
    <div class="container">
        <div class="d-flex flex-column">
            <h5 class="lead text-info text-center border-bottom mt-5 font-weight-light">HOTELS</h5>
            <div class="row">
                {% for object in user_property %}
                    {% if object.category.name == 'HOTEL' %}
                        {% include 'partials/property_datails.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <h5 class="lead text-info text-center border-bottom mt-5 font-weight-light">APARTMENTS</h5>
            <div class="row">
                {% for object in user_property %}
                    {% if object.category.name == 'APARTMENT' %}
                        {% include 'partials/property_datails.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <h5 class="lead text-info text-center border-bottom mt-5 font-weight-light">GUESTHOUSES</h5>
            <div class="row">
                {% for object in user_property %}
                    {% if object.category.name == 'GUESTHOUSE' %}
                        {% include 'partials/property_datails.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <h5 class="lead text-info text-center border-bottom mt-5 font-weight-light">RENTALS</h5>
            <div class="row">
                {% for object in user_property %}
                    {% if object.category.name == 'RENTAL' %}
                        {% include 'partials/property_datails.html' %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/rentals/property_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Property</legend>
                <h2 class="lead">Are you sure you want to delete the property "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'rentals:property_detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/rentals/property_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
    <div class="media content-section">
        <div class="media-body">
            <div class="property-metadata">
                <span class="font-weight-light">Landlord: </span>
                <a class="mr-2" href="#">{{ object.owner }}</a>
                {% if object.owner.phone_number %}
                    <small class="text-muted">{{ object.owner.phone_number }}</small>
                {% else %}
                    <small class="text-muted">{{ object.owner.user.email }}</small>
                {% endif %}
                {% if object.owner.user == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-2 mb-1" href="{% url 'rentals:property_update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-2 mb-1" href="{% url 'rentals:property_delete' object.id %}">Delete</a>
                    </div>
                {% elif user.is_tenant %}
                    <div>
                        <a class="btn btn-success btn-sm mt-1 mb-1" href="#">Apply</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="#">Cancel</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="lead property-title text-center">{{ object.name }}</h2>
            <div class="d-flex flex-row justify-content-center">
                <img class="img-fluid w-50" src="{{ object.image.url }}">
            </div>
            <p class="property-content"><span class="font-weight-light text-info">Description: </span>{{ object.description }}</p>
            <div>
                <small class="text-muted">{{ object.address }}</small> |
                <small class="text-muted">UGX {{ object.price|intcomma }}</small> |
                <small class="text-muted">{{ object.category }}</small> |
                <small class="text-muted">{{ object.date_listed|date:"F d, Y" }}</small>
            </div>
        </div>
    </div>
{% endblock content %}

templates/rentals/property_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend class="lead border-bottom mb-4 h3">Create your property</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create property</button>
            </div>
        </form>
    </div>
{% endblock %}